"""longer lists

Revision ID: 0400c819528d
Revises: 51ba0678aaa2
Create Date: 2023-06-08 10:59:03.079064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0400c819528d'
down_revision = '51ba0678aaa2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
