"""added fake data

Revision ID: 51ba0678aaa2
Revises: fddbfb2bc128
Create Date: 2023-06-07 17:06:26.425372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51ba0678aaa2'
down_revision = 'fddbfb2bc128'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
