"""added models

Revision ID: fddbfb2bc128
Revises: fa266581e624
Create Date: 2023-06-07 15:37:10.454261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fddbfb2bc128'
down_revision = 'fa266581e624'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
